name: softhebb
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  # Core Python packages
  - python
  - pip
  - setuptools
  - wheel

  # Scientific computing
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn

  # Machine learning
  - scikit-learn
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-lightning
  - tensorboard
  - tensorboardx

  # Audio processing
  - librosa
  - resampy
  - ffmpeg

  # Deep learning
  - tensorflow  # Will be overridden by pip below
  - tensorflow-estimator

  # Optimization and Tuning
  - bayesian-optimization
  - ray-core
  - ray-tune

  # NLP and additional utilities
  - spacy
  - thinc
  - kornia

  # Other useful packages
  - tqdm
  - ipykernel
  - jupyterlab
  - notebook
  - jupyter_client
  - jupyter_core
  - pyyaml
  - click
  - typer
  - packaging
  # Removed cudatoolkit for macOS ARM
  # - cudatoolkit

  # Logging and visualization
  - tensorboard
  - matplotlib-inline

  # Misc
  - joblib
  - typing-extensions
  - protobuf
  - requests
  - chardet
  - charset-normalizer
  - urllib3
  - idna

  # pip packages
  - pip:
      - efficientnet-pytorch
      - kmeans-pytorch
      - torchsummary
      - tensorflow-macos
      - tensorflow-metal
